---
title: "Urban 2015-2016"
author: "Laurent du Bois"
date: "15 décembre 2015"
output: html_document
subtitle: Petit site pour voir l'évolution du score tout au long de l'année
css: stylesheets/stylesheet.css
---

    <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">
          <a id="forkme_banner" href="https://github.com/laurentdb/WebsiteTest">View on GitHub</a>

          <h1 id="project_title">Websitetest</h1>
          <h2 id="project_tagline">Example of gh-pages use</h2>

            <section id="downloads">
              <a class="zip_download_link" href="https://github.com/laurentdb/WebsiteTest/zipball/master">Download this project as a .zip file</a>
              <a class="tar_download_link" href="https://github.com/laurentdb/WebsiteTest/tarball/master">Download this project as a tar.gz file</a>
            </section>
        </header>
    </div>

# En bref
L'idée est de montrer brièvement les statistiques de notre saison d'Urban.
```{r load, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
suppressWarnings(library(dplyr))
suppressWarnings(library(ggplot2))
source("Reformat.R")
```

# Evolution des scores
Voici l'évolution des scores en vue graphique.
```{r graph, echo=FALSE, results='asis'}
  ggplot(summary, aes(Date, Pts, color=Nom)) +geom_line()+geom_point()+labs(y="Nombre of points")
```

# Détail des scores
Ci-dessous le tableau résumant les résultats des matchs passés.
```{r anotherview, echo=FALSE}
library(DT)
DT::datatable(scores0)
```


***
footer 